# merge samples following processing with dada()

# load packages

    library("dada2")

# get file paths and parameters from command line arguments

    args = commandArgs(trailingOnly=TRUE)

    filepaths <- list(
        input_rds_list = args[1], # list of rds files generated by snakemake rule
        output_rds = args[2]  # save sequence table to rds file
    )

# read in file names

    filepaths$input_rds_files <- scan(filepaths$input_rds_list, character())
    # extract sample names from filepaths
    names(filepaths$input_rds_files) <- sub('.rds$', '', basename(filepaths$input_rds_files))

# read in merged pairs from each individual sample's rds file

    all.merged.samples <- sapply(filepaths$input_rds_files, simplify = FALSE, readRDS)

# make sequence table and save to file

    sequence.table <- makeSequenceTable(all.merged.samples)
    saveRDS(sequence.table, file = filepaths$output_rds)

# report distribution of sequence lengths

    table(nchar(getSequences(sequence.table)))
